/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */


import javax.swing.JTextField;
import javax.swing.*;

/**
 *
 * @author isabe
 */
public class UpdateDialogForm extends javax.swing.JDialog {

    /**
     * Creates new form UpdateDialogForm
     */
    
    // Assuming these are class-level variables in your UpdateDialogForm class
    private String originalName;
    private String originalPrice;
    private String originalQuantity;
    
    private int productId;

// This method should be called when you open the dialog and populate the fields
    public void populateFields(String name, String price, String quantity) {
        originalName = name;
        originalPrice = price;
        originalQuantity = quantity;
        UpdateNameTextField.setText(name);
        UpdatePriceTextField.setText(price);
        UpdateQuantityTextField.setText(quantity);
    }   
    
    public void setProductId(int productId) {
        this.productId = productId;
    }
    
    public UpdateDialogForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UpdateNameLabel = new javax.swing.JLabel();
        UpdateNameTextField = new javax.swing.JTextField();
        UpdatePriceLabel = new javax.swing.JLabel();
        UpdatePriceTextField = new javax.swing.JTextField();
        UpdateQuantityLabel = new javax.swing.JLabel();
        UpdateQuantityTextField = new javax.swing.JTextField();
        UpdateSubmitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        UpdateNameLabel.setText("Name");

        UpdatePriceLabel.setText("Price");

        UpdateQuantityLabel.setText("Quantity");

        UpdateSubmitButton.setText("Submit");
        UpdateSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateSubmitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UpdateNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdatePriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateQuantityLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UpdateSubmitButton)
                    .addComponent(UpdateNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdatePriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateQuantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateNameLabel)
                    .addComponent(UpdateNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdatePriceLabel)
                    .addComponent(UpdatePriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateQuantityLabel)
                    .addComponent(UpdateQuantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(UpdateSubmitButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateSubmitButtonActionPerformed
        // TODO add your handling code here:
        String newName = UpdateNameTextField.getText();
        String newPriceStr = UpdatePriceTextField.getText();
        String newQuantityStr = UpdateQuantityTextField.getText();

        if (newName.equals(originalName) && newPriceStr.equals(originalPrice) && newQuantityStr.equals(originalQuantity)) 
        {
            JOptionPane.showMessageDialog(this, "No changes detected.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
    
        try 
        {
            double newPrice = Double.parseDouble(newPriceStr);
            int newQuantity = Integer.parseInt(newQuantityStr);
        
            // Use the productId that was set when the dialog was instantiated
            DatabaseConnector.updateProductInDatabase(this.productId, newName, newPrice, newQuantity);
        
            JOptionPane.showMessageDialog(this, "Product updated successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        } 
        catch (NumberFormatException ex) 
        {
            JOptionPane.showMessageDialog(this, "Please enter valid numbers for price and quantity.", "Input Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_UpdateSubmitButtonActionPerformed

    public void setNameField (String name)
    {
        this.UpdateNameTextField.setText(name);
    }
    
    public void setPriceField (String price)
    {
        this.UpdatePriceTextField.setText(price);
    }
    
    public void setQuantityField (String quantity)
    {
        this.UpdateQuantityTextField.setText(quantity);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateDialogForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateDialogForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateDialogForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateDialogForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UpdateDialogForm dialog = new UpdateDialogForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel UpdateNameLabel;
    private javax.swing.JTextField UpdateNameTextField;
    private javax.swing.JLabel UpdatePriceLabel;
    private javax.swing.JTextField UpdatePriceTextField;
    private javax.swing.JLabel UpdateQuantityLabel;
    private javax.swing.JTextField UpdateQuantityTextField;
    private javax.swing.JButton UpdateSubmitButton;
    // End of variables declaration//GEN-END:variables
}
